# Generated by Django 5.1.5 on 2025-06-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0039_paymentmethod_paymentreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreport',
            options={'permissions': [('select_custom_seller_paymentreport', 'Can select custom seller'), ('view_all_contacts_paymentreport', 'Can view all contacts')]},
        ),
    ]
