# Generated by Django 5.1.5 on 2025-06-17 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0040_alter_paymentreport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
