# Generated by Django 5.1.5 on 2025-06-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0041_alter_paymentreport_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreport',
            options={'permissions': [('select_custom_seller_paymentreport', 'Can select custom seller'), ('view_all_contacts_paymentreport', 'Can view all contacts'), ('view_own_paymentreport', 'Can view its own payment report')]},
        ),
    ]
