# Generated by Django 5.1.5 on 2025-06-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0042_alter_paymentreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreport',
            options={'permissions': [('select_custom_seller_paymentreport', 'Can select custom seller'), ('view_all_contacts_paymentreport', 'Can view all contacts'), ('view_own_paymentreport', 'Can view its own payment report'), ('view_export_paymentreport', 'Can export payment report')]},
        ),
    ]
