# Generated by Django 5.1.5 on 2025-07-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0046_alter_user_options_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_staff_user', 'Can view staff user'), ('change_staff_user', 'Can change staff user'), ('delete_staff_user', 'Can delete staff user'), ('add_staff_user', 'Can add staff user'), ('view_settings_user', 'Can view settings'), ('view_advanced_homepage_user', 'Can view advanced homepage'), ('change_own_email_user', 'Can change its own email'), ('change_own_name_user', 'Can change its own name'), ('change_own_phonenumber_user', 'Can change its own phonenumber'), ('change_own_cardid_user', 'Can change its own card id'), ('change_own_address_user', 'Can change its own address')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
