# Generated by Django 5.1.5 on 2025-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0047_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreport',
            options={'permissions': [('select_custom_seller_paymentreport', 'Can select custom seller'), ('view_all_contacts_paymentreport', 'Can view all contacts'), ('view_own_paymentreport', 'Can view its own payment report'), ('view_export_paymentreport', 'Can export payment report'), ('change_status_paymentreport', 'Can change payment report status')]},
        ),
        migrations.AddField(
            model_name='paymentreport',
            name='status',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=16),
        ),
    ]
