# Generated by Django 5.1.5 on 2025-08-20 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0050_enable_trigram'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlegraSeller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identification', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactAddRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('identification', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('phonePrimary', models.CharField(max_length=64)),
                ('seller', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_add_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ContactAddRequest',
                'verbose_name_plural': 'ContactAddRequests',
                'permissions': [('view_approve_contactaddrequest', 'Can approve contact add request')],
            },
        ),
    ]
